### ISSUE TITLE
AndroidX, Fragment

### ISSUE THREAD

**Issue by dunda123** [sensorberg-dev/permission-bitte#2]
Hi.
I have been using your library for a long time.

Now. I create project with AndroidX and Android Navigation. In my MainActivity I implement BitteBitte interface and ask permission. In activity is one Fragment. When i rotate device application end with failure:

java.lang.IllegalStateException: Failure saving state: active PermissionBitteImpl{88b1128 (88205615-1a41-4998-941c-b4725075fd01) PERMISSION_BITTE} was removed from the FragmentManager
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2315)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:150)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:496)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
        at android.app.Activity.performSaveInstanceState(Activity.java:1507)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1308)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5045)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4968)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

Thanks for the help.
Zdeněk.

**Comment by budius** [comment]
Hi,
I'm happy the lib is working nice for you. You know, we post those open source code and never know if anyone uses.

I haven't migrated my work stuff to AndroidX yet (should be on it soon-ish) and will definitely have to change this library too.

On the migration docs (https://developer.android.com/jetpack/androidx/migrate) they tell to use those flags on Gradle:

```
android.useAndroidX=true
android.enableJetifier=true
```

Did you try that?

**Comment by dunda123** [comment]
This:
```
android.useAndroidX=true
android.enableJetifier=true
```
I already have this setting.

I removed the error by adding the code to the snippet:

```
    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
    }
```

Probably a problem with android navigation.
Thx. Z.

**Comment by budius** [comment]
hey @dunda123  https://github.com/sensorberg-dev/permission-bitte/commit/6796ecbc971d381090ecb59e68d9c3acd06071fb

we've updated to androidx, just move to 0.3.0
